unitary_to_county = {

/* England */
'Luton': 'Bedfordshire',
'Bedford': 'Bedfordshire',
'Central Bedfordshire': 'Bedfordshire',
'West Berkshire': 'Berkshire',
'Reading': 'Berkshire',
'Wokingham': 'Berkshire',
'Bracknell Forest': 'Berkshire',
'Windsor and Maidenhead': 'Berkshire',
'Slough': 'Berkshire',
'Bristol': 'Bristol',
'Milton Keynes': 'Buckinghamshire',
'Peterborough': 'Cambridgeshire',
'Cheshire West and Chester': 'Cheshire',
'Cheshire East': 'Cheshire',
'Warrington': 'Cheshire',
'Halton': 'Cheshire',
'Isles of Scilly': 'Cornwall',
'Derby': 'Derbyshire',
'Torbay': 'Devon',
'Plymouth': 'Devon',
'Poole': 'Dorset',
'Bournemouth': 'Dorset',
'Darlington': 'Durham',
'Stockton-on-Tees': 'Durham / North Yorkshire',
'Hartlepool': 'Durham',
'Kingston upon Hull': 'East Riding of Yorkshire',
'Brighton and Hove': 'East Sussex',
'Thurrock': 'Essex',
'Southend-on-Sea': 'Essex',
'South Gloucestershire': 'Gloucestershire',
'Bolton': 'Greater Manchester',
'Bury': 'Greater Manchester',
'Manchester': 'Greater Manchester',
'Oldham': 'Greater Manchester',
'Rochdale': 'Greater Manchester',
'Salford': 'Greater Manchester',
'Stockport': 'Greater Manchester',
'Tameside': 'Greater Manchester',
'Trafford': 'Greater Manchester',
'Wigan': 'Greater Manchester',
'Southampton': 'Hampshire',
'Portsmouth': 'Hampshire',
'Medway': 'Kent',
'Blackpool': 'Lancashire',
'Blackburn with Darwen': 'Lancashire',
'Leicester': 'Leicestershire',
'North Lincolnshire': 'Lincolnshire',
'North East Lincolnshire': 'Lincolnshire',
'Knowsley': 'Merseyside',
'Liverpool': 'Merseyside',
'St Helens': 'Merseyside',
'Sefton': 'Merseyside',
'Wirral': 'Merseyside',
'Redcar and Cleveland': 'North Yorkshire',
'Middlesbrough': 'North Yorkshire',
'York': 'North Yorkshire',
'Nottingham': 'Nottinghamshire',
'Telford and Wrekin': 'Shropshire',
'Bath and North East Somerset': 'Somerset',
'North Somerset': 'Somerset',
'Sheffield': 'South Yorkshire',
'Barnsley': 'South Yorkshire',
'Doncaster': 'South Yorkshire',
'Rotherham': 'South Yorkshire',
'Stoke-on-Trent': 'Staffordshire',
'Newcastle upon Tyne': 'Tyne and Wear',
'Gateshead': 'Tyne and Wear',
'North Tyneside': 'Tyne and Wear',
'South Tyneside': 'Tyne and Wear',
'Sunderland': 'Tyne and Wear',
'Birmingham': 'West Midlands',
'Coventry': 'West Midlands',
'Dudley': 'West Midlands',
'Sandwell': 'West Midlands',
'Solihull': 'West Midlands',
'Walsall': 'West Midlands',
'Wolverhampton': 'West Midlands',
'Wakefield': 'West Yorkshire',
'Kirklees': 'West Yorkshire',
'Calderdale': 'West Yorkshire',
'Bradford': 'West Yorkshire',
'Leeds': 'West Yorkshire',
'Swindon': 'Wiltshire',

/* Scotland */
'Clackmannanshire': 'Central',
'Falkirk': 'Central',
'Stirling': 'Central',
'Aberdeenshire': 'Grampian',
'Aberdeen': 'Grampian',
'Moray': 'Grampian',
'West Lothian': 'Lothian',
'Edinburgh': 'Lothian',
'Midlothian': 'Lothian',
'East Lothian': 'Lothian',
'Argyll and Bute': 'Strathclyde',
'North Ayrshire': 'Strathclyde',
'East Ayrshire': 'Strathclyde',
'South Ayrshire': 'Strathclyde',
'South Lanarkshire': 'Strathclyde',
'Inverclyde': 'Strathclyde',
'Renfrewshire': 'Strathclyde',
'West Dunbartonshire': 'Strathclyde',
'East Dunbartonshire': 'Strathclyde',
'Glasgow': 'Strathclyde',
'East Renfrewshire': 'Strathclyde',
'North Lanarkshire': 'Strathclyde',
'Angus': 'Tayside',
'Dundee': 'Tayside',
'Perth and Kinross': 'Tayside',

/* Wales */
'Caerphilly': 'Gwent',
'Blaenau Gwent': 'Gwent',
'Torfaen': 'Gwent',
'Monmouthshire': 'Gwent',
'Newport': 'Gwent',
'Cardiff': 'South Glamorgan',
'Vale of Glamorgan': 'South Glamorgan',
'Merthry Tydfil': 'Mid Glamorgan',
'Bridgend': 'Mid Glamorgan',
'Rhondda Cynon Taff': 'Mid Glamorgan',
'Neath Port Talbot': 'West Glamorgan',
'Swansea': 'West Glamorgan',
'Carmarthenshire': 'Dyfed',
'Ceredigion': 'Dyfed',
'Pembrokeshire': 'Dyfed',
'Isle of Anglesey': 'Gwynedd',
'Wrexham': 'Clwyd',
'Flintshire': 'Clwyd',
'Denbighshire': 'Clwyd',
'Conwy': 'Clwyd'

};
